config/routes.rb
Chatter::Application.routes.draw do
  resources :messages

  root :to => "messages#index"

end

app/models/message.rb
# -*- encoding : utf-8 -*-
class Message < ActiveRecord::Base
  attr_accessible :content
  validates :content, :presence => true
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
# -*- encoding : utf-8 -*-
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
	  @messages = Message.all
  end

  def create
  	@message = Message.create!(params[:message])
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(params[:message])
      redirect_to @message, :notice  => "Successfully updated message."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_url, :notice => "Successfully destroyed message."
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
require "net/http"
module ApplicationHelper
  def broadcast(channel,&block)
    message = {:channel => channel, :data => capture(&block),:ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://192.168.1.21:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/helpers/error_messages_helper.rb
# -*- encoding : utf-8 -*-
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# -*- encoding : utf-8 -*-
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/messages_helper.rb
# -*- encoding : utf-8 -*-
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults, "http://192.168.1.21:9292/faye.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, :remote => true  do |f| %>
  <p>
    <%= f.text_field :content %>
  </p>
  <p><%= f.submit "Send Message" %></p>
<% end %>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  <%= message.content %>
</li>

app/views/messages/create.js.erb
<% broadcast "/messages/new" do  %>
$("#chat").append("<%= escape_javascript render(@message) %>");
<% end %>
$("#new_message")[0].reset();

app/views/messages/edit.html.erb
<% title "Edit Message" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @message %> |
  <%= link_to "View All", messages_path %>
</p>

app/views/messages/index.html.erb
<% title "Messages" %>

<table>
  <tr>
    <th>Content</th>
  </tr>
  <% for message in @messages %>
    <tr>
      <td><%= message.content %></td>
      <td><%= link_to "Show", message %></td>
      <td><%= link_to "Edit", edit_message_path(message) %></td>
      <td><%= link_to "Destroy", message, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Message", new_message_path %></p>

app/views/messages/new.html.erb
<% title "Chat" %>
<ul id="chat">
  <%= render @messages %>
</ul>
<%= render 'form' %>

app/views/messages/show.html.erb
<% title "Message" %>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <%= link_to "Edit", edit_message_path(@message) %> |
  <%= link_to "Destroy", @message, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", messages_path %>
</p>